[project]
name = "lichen"
version = "0.0.1"
description = "CLI for Lichen Stack"
authors = [{ name = "Samuel Mason" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
