# Meta Data
[[default]]
version = "0.0.1"
description = "Absolute MVP Lichen Stack file tree."


# Global Scope
[[default.nodes]]
type = "file"
path = ".lichen/registry.toml"
template = "lichen/scaffold/templates/files/lichen_registry.toml.template"

[[default.nodes]]
type = "file"
path = ".gitignore"
template = "lichen/scaffold/templates/files/.gitignore.template"

[[default.nodes]]
type = "file"
path = ".env.example"
template = "lichen/scaffold/templates/files/.env.example.template"

[[default.nodes]]
type = "file"
path = "pyproject.toml"
template = "lichen/scaffold/templates/files/pyproject.toml.template"

[[default.nodes]]
type = "file"
path = "requirements.txt"
template = "lichen/scaffold/templates/files/requirements.txt.template"

[[default.nodes]]
type = "file"
path = "README.md"
template = "lichen/scaffold/templates/files/README.md.template"

[[default.nodes]]
type = "file"
path = "global.config.toml"
template = "lichen/scaffold/templates/files/global.config.toml.template"


# Gateway Service
[[default.nodes]]
type = "file"
path = "services/gateway/src/main.py"

[[default.nodes]]
type = "file"
path = "services/gateway/src/routes.py"

[[default.nodes]]
type = "file"
path = "services/gateway/requirements.txt"

[[default.nodes]]
type = "file"
path = "services/gateway/local.config.toml"
[[default.nodes]]
type = "file"
path = "services/gateway/.env.example"


# Worker Service
[[default.nodes]]
type = "file"
path = "services/worker/src/main.py"

[[default.nodes]]
type = "file"
path = "services/worker/src/routes.py"

[[default.nodes]]
type = "file"
path = "services/worker/requirements.txt"

[[default.nodes]]
type = "file"
path = "services/worker/local.config.toml"
[[default.nodes]]
type = "file"
path = "services/worker/.env.example"


# Shared modules
[[default.nodes]]
type = "file"
path = "shared/utils.py"

[[default.nodes]]
type = "file"
path = "shared/logging.py"
